# Generated by Django 3.2 on 2022-03-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingaction',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='This field changes according to the type of action', verbose_name='extra'),
        ),
    ]
