version: '3.8'

services:

  django:
    ports:
      - "8000:8000"
    command: /start
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14
  redis:
    image: redis:5


