# Generated by Django 4.1.7 on 2023-11-24 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('db_status', models.CharField(choices=[('CREATED', 'Created'), ('DELETED', 'Deleted')], default='CREATED', max_length=20, verbose_name='Estado de existencia en la base de datos')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('geofence', models.JSONField(blank=True, help_text='Ingresar un array de jsons [{lat : --,lng : --}]', null=True, verbose_name='GEO-cerca')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('db_status', models.CharField(choices=[('CREATED', 'Created'), ('DELETED', 'Deleted')], default='CREATED', max_length=20, verbose_name='Estado de existencia en la base de datos')),
                ('plate', models.CharField(max_length=8, verbose_name='Placa')),
                ('brand', models.CharField(max_length=150, verbose_name='Marca')),
                ('model', models.IntegerField(blank=True, null=True, verbose_name='Modelo (año)')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='vehiculos/%Y%m%d', verbose_name='Fotografía')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('db_status', models.CharField(choices=[('CREATED', 'Created'), ('DELETED', 'Deleted')], default='CREATED', max_length=20, verbose_name='Estado de existencia en la base de datos')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('geo_route', models.JSONField(blank=True, help_text='Ingresar un array de jsons [{lat : --,lng : --}]', null=True, verbose_name='Ruta GPS')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_area', to='ciudata.area')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='AssignedVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Fecha asignación')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_vehicle', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to='ciudata.vehicle')),
            ],
            options={
                'verbose_name': 'Vehículo asignado',
                'verbose_name_plural': 'Vehículos asignados',
                'db_table': 'asigned_vehicle',
            },
        ),
        migrations.CreateModel(
            name='AssignedRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('assigned_detail', models.TextField(blank=True, null=True, verbose_name='Detalle de asignación de ruta')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Fecha asignación de ruta')),
                ('status', models.CharField(choices=[('Asigned', 'Asigned'), ('Comleted', 'Comleted'), ('Deleted', 'Deleted')], default='CREATED', max_length=20, verbose_name='Estado de asignación')),
                ('completed_detail', models.TextField(blank=True, null=True, verbose_name='Detalle de ruta completado')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de ruta completado')),
                ('geo_route', models.JSONField(blank=True, help_text='Ingresar un array de jsons [{lat : --,lng : --}]', null=True, verbose_name='Ruta real completado')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assigned', to='ciudata.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_route', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta asignada',
                'verbose_name_plural': 'Rutas asignadas',
                'db_table': 'asigned_route',
            },
        ),
    ]
