# Generated by Django 4.1.7 on 2023-11-28 01:11

import apps.contrib.utils.strings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudata', '0002_alter_vehicle_plate_alter_vehicle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(default=apps.contrib.utils.strings.get_uuid, unique=True, verbose_name='Slug'),
        ),
    ]
