# Generated by Django 4.1.7 on 2023-11-29 16:39

import apps.contrib.utils.strings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudata', '0003_alter_vehicle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(default=apps.contrib.utils.strings.get_uuid, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='assignedroute',
            name='slug',
            field=models.SlugField(default=apps.contrib.utils.strings.get_uuid, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='route',
            name='slug',
            field=models.SlugField(default=apps.contrib.utils.strings.get_uuid, unique=True, verbose_name='Slug'),
        ),
    ]
