# Generated by Django 4.1.7 on 2023-12-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciudata', '0004_alter_area_slug_alter_assignedroute_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datetime', models.DateTimeField(help_text='Fecha y hora del punto GPS captado en el trackeo', verbose_name='Fecha y hora')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lng', models.FloatField(verbose_name='Longitud')),
                ('assigned_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traking_assigned_route', to='ciudata.assignedroute', verbose_name='Ruta asignada')),
            ],
            options={
                'verbose_name': 'Trackeo',
                'verbose_name_plural': 'Trackeos',
                'db_table': 'tracking',
            },
        ),
    ]
