# Generated by Django 4.1.7 on 2023-12-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudata', '0005_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedroute',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='ASSIGNED', max_length=20, verbose_name='Estado de asignación'),
        ),
    ]
