# Generated by Django 4.1.7 on 2024-01-04 13:38

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudata', '0006_alter_assignedroute_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='assignedroute',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadata'),
        ),
    ]
