# Generated by Django 4.1.7 on 2024-01-18 17:22

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudata', '0007_route_metadata_alter_assignedroute_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedroute',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ruta asignada', 'verbose_name_plural': 'Rutas asignadas'},
        ),
        migrations.AlterModelOptions(
            name='assignedvehicle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vehículo asignado', 'verbose_name_plural': 'Vehículos asignados'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterModelOptions(
            name='tracking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trackeo', 'verbose_name_plural': 'Trackeos'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AddField(
            model_name='tracking',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='assignedvehicle',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadata'),
        ),
    ]
